import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

// esbuild matches an external against the exact specifier, so a builtin has to
// be listed under both spellings. A handful of entries ("node:sqlite", …) are
// only ever spelled with the prefix, so don't prefix them twice.
const nodeBuiltins = builtinModules.flatMap((name) =>
	name.startsWith("node:") ? [name] : [name, `node:${name}`]
);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: false,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
